version: '3'

services:
  messageStore:
    build:
      context: .
      dockerfile: Dockerfile
    image: message_app:latest
    container_name: message_app
    environment:
      APP_PORT: 9000
      MS_DB_PASS:
      MS_DB_USER:
      MS_DB_HOST:
    ports:
      - "9000:9000"
    command: npm start
