version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 'Build Images'
          command: 'docker-compose build -f test/docker-compose.yml'
      - run:
          name: 'Test'
          command: 'docker-compose -f test/docker-compose.yml up -d messageStore'
      - run:
          name: 'Fetch artifacts'
          command: 'docker cp "$(docker-compose -f test/docker-compose.yml ps -q messageStore)":coverage.lcov coverage.lcov'
      - codecov/upload:
          file: 'coverage.lcov'
