version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 'Build Images'
          command: 'docker-compose -f test/docker-compose.yml build '
      - run:
          name: 'Test'
          command: 'docker-compose -f test/docker-compose.yml run messageStore'
      - codecov/upload:
          file: '/tmp/coverage.lcov'
